<?php

/*
 * Defines some basic CyCo stuff.
 */

/**
 * Implements hook_menu.
 */
//function cybercourse_groups_menu() {
//  $items = array();
//  $items['admin/config/cybercourse'] = array(
//    'title' => 'Cybercourse',
//    'description' => 'Configuration of the Cybercourse system.',
//    'page callback' => 'system_admin_menu_block_page',
//    'access arguments' => array('administer site configuration'),
//    'file' => 'system.admin.inc',
//    'file path' => drupal_get_path('module', 'system'),
//  );
//  $items['admin/config/cybercourse/base'] = array(
//    'title' => 'Cybercourse base settings',
//    'description' => 'Base configuration of the Cybercourse system.',
//    'page callback' => 'drupal_get_form',
//    'page arguments' => array('cybercourse_base_settings_form'),
//    'access arguments' => array('administer site configuration'),
////    'type' => MENU_DEFAULT_LOCAL_TASK,
//  );
//  return $items;
//}

function cybercourse_groups_render_basic_list() {
//  $html = views_embed_view('cybercourse_user_groups', 'user_groups_for_cp');
  $name = 'cybercourse_user_groups';
  $display_id = 'user_groups_for_cp';  
  $view = views_get_view($name);
  if (!$view || !$view->access($display_id)) {
    return '<p>Not found or access denied</p>';
  }
  $view_content = $view->preview($display_id);
  return $view_content;
}

/**
 * Get the groups of a given type that a user has a given role in.
 * @global stdClass $user The current user.
 * @param string $group_type Type of group, e.g., class.
 * @param string $role_name Role name, e.g., grader.
 * @param stdClass $user_to_check User to check. Defaults to current user.
 * @return array Group ids.
 */
function cybercourse_groups_get_groups_by_role( 
    $group_type, $role_name, $user_to_check = NULL ) {
  if ( is_null($user_to_check) ) {
    global $user;
    $user_to_check = $user;
  }
  //Find groups the user is in.
  $user_group_gids = og_get_groups_by_user($user_to_check, $group_type);
  $user_groups = array();
  foreach ( $user_group_gids as $gid ) {
    $roles = og_get_user_roles($group_type, $gid);
    if ( in_array($role_name, $roles) ) {
      $user_groups[] = $gid;
    }
  }
  return $user_groups;
}


/**
 * Get all users of a group.
 * See http://codekarate.com/blog/drupal-7-getting-all-members-organic-group
 */
function cybercourse_groups_get_group_users($gid) {
  $query = db_select('users', 'u');
  $query
    ->condition('u.uid', 0, '<>')
    ->condition('u.status', 1, '=')
    ->fields('u', array('uid', 'name'))
    ->join('og_membership', 'ogm', "ogm.gid = :gid AND u.uid = ogm.etid AND ogm.entity_type = 'user'", array(':gid' => $gid));
  return $query->execute();
}

/**
 * Get the names of group(s) given their id(s).
 * @param int or array $gids A group id, or an array of them.
 * @return string or array One group name, or an array of names,
 *    keyed by group id.
 */
function cybercourse_groups_get_group_names( $gids ) {
  $query = db_select('node', 'n')
      ->fields('n', array('nid', 'title'));
  //Add a condition for an array, or a single value.
  if ( is_array( $gids ) ) {
    $query->condition('n.nid', $gids, 'IN');
  }
  else {
    $query->condition('n.nid', $gids);
  }
  $records = $query->execute();
  if ( is_array( $gids ) ) {
    //Array passed. Return array of nid/title pairs.
    $result = array();
    while ( $record = $records->fetchAssoc() ) {
      $result[ $record['nid'] ] = $record['title'];
    }
  }
  else {
    //Just one gid passed. Return its title.
    $record = $records->fetchAssoc();
    $result = $record['title'];
  }
  return $result;
}

/**
 * Get the members of group(s) given their id(s).
 * @param int or array $gids A group id, or an array of them.
 * @return array Entity ids (one gid), or array of arrays of member ids,
 *    keyed by group id.
 */
function cybercourse_groups_get_group_members( $gids ) {
  $query = db_select('og_membership', 'ogm')
      ->fields('ogm', array('gid', 'etid'));
  //Add a condition for an array, or a single value.
  if ( is_array( $gids ) ) {
    $query->condition('ogm.gid', $gids, 'IN');
  }
  else {
    $query->condition('ogm.gid', $gids);
  }
  $records = $query->execute();
  if ( is_array( $gids ) ) {
    //Array passed. Return array of arrays.
    $result = array();
    while ( $record = $records->fetchAssoc() ) {
      $gid = $record['gid'];
      $etid = $record['etid'];
      if ( ! isset( $result[ $gid ] ) ) {
        $result[ $gid ] = array();
      }
      $result[ $gid ][] = $etid;
    }
  }
  else {
    //Just one gid passed. Return its members.
    $result = array();
    while ( $record = $records->fetchAssoc() ) {
      $etid = $record['etid'];
      $result[] = $etid;
    }
  }
  return $result;
}

