<?php

/*
 * Defines some basic CyCo stuff.
 */

//Load the error handler.
require_once 'cybercourse_error_handler.inc';
//Load utilities library.
require_once 'cybercourse_base_utilities.inc';

/**
 * Implements hook_menu.
 */
function cybercourse_base_menu() {
  $items = array();
  $items['admin/config/cybercourse'] = array(
    'title' => 'Cybercourse',
    'description' => 'Configuration of the Cybercourse system.',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer site configuration'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  $items['admin/config/cybercourse/base'] = array(
    'title' => 'Cybercourse base settings',
    'description' => 'Base configuration of the Cybercourse system.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cybercourse_base_settings_form'),
    'access arguments' => array('administer site configuration'),
//    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  return $items;
}

/**
 * Implements hook_permission.
 */
//function cybercourse_exercise_permission() {
//  return array(
//    'administer cybercourse' => array(
//      'title' => t('Administer Cybercourse'),
//      'restrict access' => TRUE,
//    ),
//  );
//}
//
/**
 * Define base config form.
 */
function cybercourse_base_settings_form($form, &$form_state) {
  $form['nothing'] = array(
    '#type' => 'markup',
    '#markup' => 'Nothing',
  );
  return $form;
}

/**
 * Handle an error.
 * @staticvar CyberCourseErrorHandler $error_handler Error handling class.
 * @param string $error_code Code, e.g., ACCESS_DENIED.
 * @param string $explanation Why? Oh, god, WHY?
 */
function cybercourse_base_handle_error( 
      $error_code = 'UNKNOWN_ERROR',
      $explanation = 'Something bad.'
    ) {
  static $error_handler = NULL;
  if ( is_null($error_handler) ) {
    $error_handler = new CyberCourseErrorHandler();
  }
  $error_handler->reportError($error_code, $explanation);
}