<?php

/**
 * Implements hook_menu.
 */
function cybercourse_exercise_test_menu() {
  $items = array();
  $items['cyco-et1'] = array(
    'title' => 'Exercise test 1',
    'page callback' => 'cyco_et1',
    'access callback' => '_cybercourse_exercise_test_access',
    'type' => MENU_CALLBACK,
  );
  $items['cyco-et2'] = array(
    'title' => 'Exercise test 2',
    'page callback' => 'cyco_et2',
    'access callback' => '_cybercourse_exercise_test_access',
    'type' => MENU_CALLBACK,
  );
  $items['cyco-et3'] = array(
    'title' => 'Exercise test 3',
    'page callback' => 'cyco_et3',
    'access callback' => '_cybercourse_exercise_test_access',
    'type' => MENU_CALLBACK,
  );
  $items['cyco-et4'] = array(
    'title' => 'Exercise test 4',
    'page callback' => 'cyco_et4',
    'access callback' => '_cybercourse_exercise_test_access',
    'type' => MENU_CALLBACK,
  );
  $items['cyco-et5'] = array(
    'title' => 'Exercise test 5',
    'page callback' => 'cyco_et5',
    'access callback' => '_cybercourse_exercise_test_access',
    'type' => MENU_CALLBACK,
  );
  $items['cyco-et6'] = array(
    'title' => 'Exercise test 6',
    'page callback' => 'cyco_et6',
    'access callback' => '_cybercourse_exercise_test_access',
    'type' => MENU_CALLBACK,
  );
  $items['cyco-et7'] = array(
    'title' => 'Exercise test 7',
    'page callback' => 'cyco_et7',
    'access callback' => '_cybercourse_exercise_test_access',
    'type' => MENU_CALLBACK,
  );
  $items['cyco-et8'] = array(
    'title' => 'Exercise test 8',
    'page callback' => 'cyco_et8',
    'access callback' => '_cybercourse_exercise_test_access',
    'type' => MENU_CALLBACK,
  );
  $items['cyco-et9'] = array(
    'title' => 'Exercise test 9',
    'page callback' => 'cyco_et9',
    'access callback' => '_cybercourse_exercise_test_access',
    'type' => MENU_CALLBACK,
  );
  $items['cyco-et10'] = array(
    'title' => 'Exercise test 10',
    'page callback' => 'cyco_et10',
    'access callback' => '_cybercourse_exercise_test_authenticated_user',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

//Return true if the user can access tests.
function _cybercourse_exercise_test_access() {
  global $user;
  $admin_key = array_search('administrator', $user->roles);
  return $admin_key !== FALSE;
}

//Return true if the user is authenticated.
function _cybercourse_exercise_test_authenticated_user() {
  global $user;
  $key = array_search('authenticated user', $user->roles);
  return $key !== FALSE;
}


/**
 * Test function.
 */
function cyco_et1() {
  global $base_url;
  drupal_add_js(
      drupal_get_path('module', 'cybercourse_exercise_test')
        . '/js/cyco_et1.js'
  );
  return '<div id="t1"></div>';
}

/**
 * Test function.
 */
function cyco_et2() {
  global $base_url;
  drupal_add_js(
      drupal_get_path('module', 'cybercourse_exercise_test')
        . '/js/cyco_et2.js'
  );
  return '<div id="t2"></div>';
}

/**
 * Test function.
 */
function cyco_et3() {
  drupal_add_library('system', 'ui.dialog');
  //Load Fancytree.
  $ftLibraryInfo = libraries_load('fancytree');
  $numFilesLoaded = libraries_load_files($ftLibraryInfo);
//return;
  if ( $numFilesLoaded <= 0 ) {
    $mess = t('Error: no Fancytree files loaded. Is Fancytree installed?');
    watchdog('cybercourse_exercise', $mess);
    services_error($mess, 666);
  }
  drupal_add_js(
      drupal_get_path('module', 'cybercourse_exercise_test')
        . '/js/cyco_et3.js'
  );
  return '<div id="t3">asdf</div>';
}

/**
 * Test function.
 */
function cyco_et4() {
  drupal_add_library('system', 'ui.dialog');
  //Load Fancytree.
  $ftLibraryInfo = libraries_load('fancytree');
  $numFilesLoaded = libraries_load_files($ftLibraryInfo);
//return;
  if ( $numFilesLoaded <= 0 ) {
    $mess = t('Error: no Fancytree files loaded. Is Fancytree installed?');
    watchdog('cybercourse_exercise', $mess);
    services_error($mess, 666);
  }
  drupal_add_js(
      drupal_get_path('module', 'cybercourse_exercise_test')
        . '/js/cyco_et4.js'
  );
  drupal_add_css(
      drupal_get_path('module', 'cybercourse_exercise_test')
        . '/css/cyco_et4.css'
  );
  return '<div id="t4">asdf</div>';
}

/**
 * Test function.
 */
function cyco_et5() {
  drupal_add_library('system', 'ui.dialog');
  //Load Fancytree.
  $ftLibraryInfo = libraries_load('fancytree');
  $numFilesLoaded = libraries_load_files($ftLibraryInfo);
//return;
  if ( $numFilesLoaded <= 0 ) {
    $mess = t('Error: no Fancytree files loaded. Is Fancytree installed?');
    watchdog('cybercourse_exercise', $mess);
    services_error($mess, 666);
  }
  drupal_add_js(
      drupal_get_path('module', 'cybercourse_exercise_test')
        . '/js/cyco_et5.js'
  );
  drupal_add_css(
      drupal_get_path('module', 'cybercourse_exercise_test')
        . '/css/cyco_et5.css'
  );
  return '<div id="t5">asdf</div>';
}

/**
 * Test function.
 */
function cyco_et6() {
  drupal_add_library('system', 'ui.dialog');
  //Load Fancytree.
  $ftLibraryInfo = libraries_load('fancytree');
  $numFilesLoaded = libraries_load_files($ftLibraryInfo);
  if ( $numFilesLoaded <= 0 ) {
    $mess = t('Error: no Fancytree files loaded. Is Fancytree installed?');
    watchdog('cybercourse_exercise', $mess);
    services_error($mess, 666);
  }
  drupal_add_js(
      drupal_get_path('module', 'cybercourse_exercise_test')
        . '/js/cyco_et6.js'
  );
  drupal_add_css(
      drupal_get_path('module', 'cybercourse_exercise_test')
        . '/css/cyco_et6.css'
  );
  $html = theme( 'select_rubric_item' );
  $html = '<p id="t6">asdf</p>' . $html;
  return $html;
}

/**
 * Test function.
 */
function cyco_et7() {
  drupal_add_library('system', 'ui.dialog');
  drupal_add_js(
      drupal_get_path('module', 'cybercourse_exercise_test')
        . '/js/cyco_et7.js'
  );
  drupal_add_css(
      drupal_get_path('module', 'cybercourse_exercise_test')
        . '/css/cyco_et7.css'
  );
  $html = <<<EOT
<div id="t7">
    nid: <input type="text" id="nid"><br>
    title: <input type="text" id="title"><br>
    <button id="test">Test</button>
</div>
EOT;
  return $html;
}

/**
 * Test function.
 */
function cyco_et8() {
  drupal_add_library('system', 'ui.dialog');
  drupal_add_js(
      drupal_get_path('module', 'cybercourse_exercise_test')
        . '/js/cyco_et8.js'
  );
  $html = <<<EOT
<div id="t8">
    nid: <input type="text" id="nid"><br>
    title: <input type="text" id="title"><br>
    <button id="test">Test</button>
</div>
EOT;
  return $html;
}

/**
 * Test function.
 */
function cyco_et9() {
//  drupal_add_library('system', 'ui.dialog');
  drupal_add_js(
      drupal_get_path('module', 'cybercourse_exercise_test')
        . '/js/cyco_et9.js'
  );
  $html = <<<EOT
<div id="t9">
  <a href="/node/add/exercise-submission" data-target="popup">Test</a>
</div>
EOT;
  return $html;
}

/**
 * Test function.
 */
function cyco_et10() {
  drupal_add_library('system', 'ui.dialog');
  drupal_add_js(
      drupal_get_path('module', 'cybercourse_exercise_test')
        . '/js/cyco_et10.js'
  );
  $html = <<<EOT
<div id="t10">
    student uid: <input type="text" id="student"><br>
    exer nid: <input type="text" id="exercise"><br>
    <button id="test">Test</button>
      <p id="loading">Loading...</p>
</div>
EOT;
  return $html;
}