<?php
define( 'RELATION_NAME_ITEM_TO_KM', 'is_part_of_knowledge_map');
define( 'DRAWING_ID_CACHE_NAME', 'knowledgemap_drawing_id_cache');

define( 'NEW_KM_ITEM_INDICATOR', '(New modal)');

module_load_include('inc', 'knowledgemap', 'knowledgemap.utils');

/**
 * Implements hook_menu.
 */
function knowledgemap_menu() {
  $items['show-km-item/%'] = array(
    'page callback' => 'knowledgemap_show_item',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  //Add a new item. Passing in the coords of the mouse click, and the 
  //nid of the KM that will own the new item.
  $items['add-km-item/%dialog_js/%/%/%'] = array(
    'page callback' => 'knowledgemap_add_item',
    'page arguments' => array(1, 2, 3, 4),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['add-done/%dialog_js'] = array(
    'page callback' => 'knowledgemap_add_done',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['edit-km-item/%'] = array(
    'page callback' => 'knowledgemap_edit_item',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['confirm-delete-km-item/%'] = array(
    'page callback' => 'knowledgemap_confirm_delete',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['delete-km-item-confirmed/%'] = array(
    'page callback' => 'knowledgemap_delete_confirmed',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}


/**
 * Implements hook_field_info(). 
 * Creates one formatter and one input widget.
 */
function knowledgemap_field_info() {
  return array(
    'knowledgemap' => array(
      'label' => t('Knowledge map'),
      'description' => 
        t('This field stores a display of a knowledge map.'),
      'default_formatter' => 'knowledgemap_formatter',
      'default_widget' => 'knowledgemap_widget',
      'instance_settings' => array(
        'default_value' => ' ',
      ),
    ),
  );
}

/**
 * Implements hook_field_is_empty().
 */
function knowledgemap_field_is_empty($item, $field) {
  if (!isset($item['knowledgemap']) || $item['knowledgemap'] === '') {
    return TRUE;
  }
  return FALSE;
}

/**
 * Implements hook_field_widget_info.
 * 
 * Describes a widget for the KM field.
 * 
 */
function knowledgemap_field_widget_info() {
    return array(
      'knowledgemap_widget' => array(
      'label' => t('Knowledge map'),
      'description' => t(
          'Allow the user to edit KMs.'),
      'field types' => array('knowledgemap'),
    ),
  );
}

/**
 * Define the widget for the KM. 
 */
function knowledgemap_field_widget_form(&$form, &$form_state, 
    $field, $instance, $langcode, $items, $delta, $element) {
  //$element contains some of the Right Stuff already. Add to it.
  $base = $element;
  //Can't add KM items on new node.
  //Is this a new node? $node is the KM node that has the widget in it.
  $new_node = TRUE;
  if ( isset( $form_state['node'] ) ) {
    if ( isset( $form_state['node']->nid ) && ! isset($node->is_new)) {
      $new_node = FALSE;
    }
  }
  if ( $new_node ) {
    $element[$delta] = array(
      '#type' => 'markup',
      '#markup' => '<p>' . t('(Add KM items after knowledge map has been created.)') . '</p>',
    ) + $base;
    return $element;
  }
  //This is a node edit.
  $node = $form_state['node'];
  drupal_add_js('misc/ajax.js');
  //What is the DOM id of the drawing area?
  $nid = $node->nid;
  $drawing_dom_id 
      = knowledgemap_compute_drawing_id( $nid );
  //Cache for later.
  knowledgemap_store_in_cache( DRAWING_ID_CACHE_NAME, $drawing_dom_id );
  $output = '';
  //Make container.
  $output .= 
         knowledgemap_edit_template($drawing_dom_id);
  //Make <div> for the drawing and item areas.
  $element[$delta] = array(
    '#type' => 'markup',
    '#markup' => $output,
  ) + $base;
  //Send the DOM ids and other things to the JS.
  $knowledgemap_rep = array(); //knowledgemap_make_km_rep($node->nid);
  $settings = array(
    'drawing_dom_id' => $drawing_dom_id,
    'km_nid' => $nid, //The nid of the KM being shown.
    'knowledgemap_rep' => $knowledgemap_rep,
  );
  drupal_add_js(
      array('knowledgemap' => $settings),
      'setting'
  );
  //Add JS libraries.
  jsplumb_add_library();
  //Add the KM drawing code.
  drupal_add_js(
      drupal_get_path('module', 'knowledgemap') 
          . '/js/knowledgemap_common.js', 
      'file'
  );
  drupal_add_js(
      drupal_get_path('module', 'knowledgemap') 
          . '/js/knowledgemap_edit.js', 
      'file'
  );
  drupal_add_css(
      drupal_get_path('module', 'knowledgemap') 
          . '/css/knowledgemap_edit.css', 
      'file'
  );
  return $element;
}

function knowledgemap_node_view($node, $view_mode, $langcode) {
  $r=5;
}

/**
 * 
 * @global type $user Logged in user.
 * @param type $ajax Is this an ajax call?
 * @param type $x X coord of the mouse click in the drawing area.
 * @param type $y Y coord of the mouse click in the drawing area.
 * @param type $km_nid Nid of the KM that will own this new item.
 * @return string
 */
function knowledgemap_add_item( $ajax, $x, $y, $km_nid ) {
  //Add the dialog library.
  drupal_add_library('dialog','dialog');
  if ( $ajax ) {
    //Make a blank node, to pass to the node add form.
    global $user;
    $new_node = (object) array(
      'title' => '(New modal)', 
        //Tells form alter code that this is a new item being created in a 
        //modal form.
      'uid' => $user->uid, 
      'name' => (isset($user->name) ? $user->name : ''), 
      'type' => 'knowledge_map_item', 
      'language' => LANGUAGE_NONE,
    );
    //Store the mouse coords in the new item.
    $new_node->field_coord_x[LANGUAGE_NONE][0]['value'] = $x;
    $new_node->field_coord_y[LANGUAGE_NONE][0]['value'] = $y;
    //Store for relation creation code.
    $new_node->implied_km = $km_nid;
    // Add the node.pages.inc so that functions from the form can be used.
    module_load_include('inc', 'node', 'node.pages');
    //Load the add form.
    $form = drupal_get_form($new_node->type . '_node_form', $new_node); 
    $html = drupal_render($form);
    //Send the form to the browser.
    print drupal_json_encode($html);
    exit;
  }
  else {
    return 'Javascript must be enabled.';
  }
}

function knowledgemap_add_done( $ajax ) {
  $output[] = dialog_command_dismiss();
  ajax_render($output);
}

function knowledgemap_form_alter(&$form, &$form_state, $form_id) {
  if ( $form_id == 'knowledge_map_item_node_form' ) {
    //The form could be in a modal, in which case the KM node the item
    //should be associated with is known.
    if ( $form['title']['#default_value'] == NEW_KM_ITEM_INDICATOR) {
      //The form is in a modal.
      $form['title']['#default_value'] = '';
      //Remove the widget for the relation that 
      //links the item to the knowledge map node. 
      unset( $form['field_knowledge_map'] );
      //Store whether his is an add or edit. Only the add needs
      //special treatment later, to create the relationship after the 
      //new nid is known.
      $node = $form_state['node'];
      $is_new_node = (!isset($node->nid) || isset($node->is_new));
      $node->knowledgemap_operation 
          = $is_new_node ? 'add' : 'edit';
      //Hide the coord fields.
      $form['field_coord_x']['#access'] = FALSE;
      $form['field_coord_y']['#access'] = FALSE;
      //Submit handler.
      $form['#submit'][] = 'knowledgemap_submit_item_form';
      //After build handler.
      //$form['#after_build'][] = 'knowledgemap_submit_item_form';
    }
  }
  
}

function knowledgemap_submit_item_form($form, &$form_state) {
  global $base_url;
//  $form_state['redirect'][] = $base_url . '/add-done/nojs';
//  unset($_REQUEST['destination'], $_REQUEST['edit']['destination']);
  $form_state['redirect'][] = drupal_get_destination();
  $form_state['redirect'][] = $base_url . '/add-done/nojs';

  unset($_GET['destination']);
  drupal_static_reset('drupal_get_destination');
  drupal_get_destination();
  
}

/**
 * Implements hook_node_insert.
 * 
 * Add a new relationship, if this is a new KM item node that was
 * created in a modal from the KM editor thing. Don't have the 
 * nid until this point.
 */
function knowledgemap_node_insert($node) {
  //Check whether this is an add operation that needs a relation to be added.
  if (    isset( $node->knowledgemap_operation )
       && $node->knowledgemap_operation == 'add'
     ) {
    //Is there an implied KM? That means the new item was created in the
    //KM GUI editor, and a KM nid has been cached for it.
    if ( isset( $node->implied_km ) ) {
      //Add a new relation. Use the implied KM nid stored earlier 
      //in the node object.
      $endpoints = array(
        array('entity_type' => 'node', 'entity_id' => $node->nid),
        array('entity_type' => 'node', 'entity_id' => $node->implied_km),
      );
      //Create new relation object.
      $new_relation = relation_create(RELATION_NAME_ITEM_TO_KM, $endpoints);
      //Save it.
      $rid = relation_save($new_relation);
      
      drupal_goto($base_url . '/add-done/nojs');
    } //End there is an implied KM nid.
  }
}