<?php

function cc_fix_br_form_lesson_node_form_alter(&$form, &$form_state) {
//  $form['thing'] = array(
//    '#markup' => '<p><button id="thing" type="button">Thing</button></p>',
//  );
//  
  if (module_invoke('ajax_markup', 'on')) {
    drupal_add_js(drupal_get_path('module', 'cc_fix_br') .'/cc_fix_br.js');
  }
}

function cc_fix_br_filter_info() {
//  $filters['markdown_wysiwyg'] = array(
//    'title' => t('Markdown WYSIWYG'),
//    'description' => t('Fix \'er up'),
//    'process callback'  => '_cc_fix_br_filter_process',
//  );
  $filters['add_line_breaks'] = array(
    'title' => t('Add line breaks'),
    'description' => t('Replace [br] with HTML line break tags.'),
    'process callback'  => '_cc_fix_br_add_line_breaks',
  );  return $filters;
}

//function _cc_fix_br_filter_process($text, $filter, $format) {
//  //Remove line feeds.
//  $text = str_replace('\n', '', $text);
//  //Replace <br />s with line feeds
//  $text = str_replace('<br />', '\n', $text);
//  return $text;
//}

function _cc_fix_br_add_line_breaks($text, $filter, $format) {
   $text = str_replace('[br]', '<br>', $text);
  return $text;
}
