<?php

/*
 * Changes to this and that.
 */

/**
 * Add the well class around image and file widgets.
 */
function cybercourse_change_things_field_widget_form_alter(
    &$element, &$form_state, $context) {
  // Add a css class to widget form elements for all fields of type mytype.
  if ($context['field']['type'] == 'image' || $context['field']['type'] == 'file') {
    // Be sure not to overwrite existing attributes.
    $element['#attributes']['class'][] = 'well';
  }
}

/**
 * Kill the book section of node edit forms for non-admins.
 */
function cybercourse_change_things_form_alter( &$form, &$form_state, $form_id ) {
  if ( stristr( $form_id, 'node_form' ) !== FALSE ) {
    if ( isset( $form['book'] ) ) {
      global $user;
      if ( ! in_array('administrator', $user->roles) ) {
        unset( $form['book']);
      }
    }
  }
}