<?php

/**
 * @file
 * Makes the nav bar that is at the bottom of each book page to also
 * appear at the top.
 */

//Default number of characters before navigation bar appears.
define('BOOKTOPNAV_DEFAULT_MIN_CHARS', 500);
//Default for whether ToC is show,
define('BOOKTOPNAV_DEFAULT_SHOW_TOC', FALSE);
//Weight for the top nav bar. Book module uses 100 for the bottom bar.
define('BOOKTOPNAV_NAV_BAR_WEIGHT', -10);

/**
 * Implementation of hook_menu().
 */
function booktopnav_menu() {
  $items['admin/settings/booktopnav'] = array(
    'title' => 'Book top navigation settings',
    'description' => 'Change how the top navigation bar behave',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('booktopnav_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'booktopnav.admin.inc',
  );
  return $items;
}

/**
 * Implementation of hook_node_view().
 *
 */
function booktopnav_node_view($node, $view_mode, $langcode) {
  if ( $view_mode == 'full' ) {
    //Is there book navigation for this code?
    if ( isset($node->content['book_navigation']) ) {
      if ( isset($node->content['body'][0]['#markup'] ) ) {
        $content = strip_tags($node->content['body'][0]['#markup']);
        //Test for minimum length.
        if (drupal_strlen($content) >= variable_get('booktopnav_min_content_length',
                                      BOOKTOPNAV_DEFAULT_MIN_CHARS)) {
          //To omit table of contents, force no children.
          $n = $node->book;
          //Turn off the ToC if configured that way.
          if ( ! variable_get('booktopnav_show_toc', BOOKTOPNAV_DEFAULT_SHOW_TOC) ) {
            $n['has_children'] = FALSE;
          }
          //Add the nav bar.
          $node->content['book_navigation_top'] = array(
              '#markup' => theme('book_navigation', 
                  array('book_link' => $n)),
            //theme('book_navigation', $n),
              '#weight' => ( $node->content['body']['#weight'] - 1 ) //BOOKTOPNAV_NAV_BAR_WEIGHT,
          );
        }
      }
    }
  }
}

/**
 * Implementation of hook_help().
 */
function booktopnav_help($path, $arg) {
  switch ($path) {
    case 'admin/settings/booktopnav':
      return '<p>'.t("The book top navigation module takes the navigation bar that
appears at the bottom of each book page, and repeats it at the top of the
page.").'</p>';
    case 'admin/help#booktopnav':
      return
  '<p>'.t("The book top navigation module takes the navigation bar that
appears at the bottom of each book page, and repeats it at the top of the
page. This can be especially useful for users who are scanning a book,
looking for something they have seen before.").'</p>'
.'<p>'.t("You can specify whether the table of contents is shown in the
top navigation bar. You can also specify
how long a page must be before the navigation bar is added.
Repeated navigation can look strange on short pages.");
  }
}

