<?php

/**
* Implements hook_init().
*/
function cybercourse_exercise_services_init() {
  
}

/**
* Implements hook_services_resources().
*/
function cybercourse_exercise_services_resources() {
  $api = array(
    
    /** Rubric item **/
    'rubric_item' => _cybercourse_exercise_def_rubric_item_services(),
    
    /** Exercise **/
    'exercise' => _cybercourse_exercise_def_exercise_services(),
    
    /** Rubic item categories **/
    'rubric_item_categories' => _cybercourse_exercise_def_category_services(),
    
    /** Exercise submission. **/
    'submission' => _cybercourse_exercise_def_sub_meta_services(),
    
    /** Feedback system. **/
    'feedback' => _cybercourse_exercise_def_feedback_services(),
      
  );
  return $api;
}


function _cybercourse_exercise_def_rubric_item_services() {
  
  $retrieve = array(
    'help' => 'Retrieves a rubric item',
    'callback' => '_exri_retrieve',
    'access callback' => '_exri_access',
    'access arguments' => array('view'),
    'access arguments append' => TRUE,
    'args' => array(
      array(
        'name' => 'id',
        'type' => 'int',
        'description' => 'The id of the rubric item to get',
        'source' => array('path' => '0'),
        'optional' => FALSE,
      ),
    ),
  );
  $create = array(
    'help' => 'Creates a rubric item',
    'callback' => '_exri_create',
    'access callback' => '_exri_access',
    'access arguments' => array('create'),
    'access arguments append' => FALSE,
    'args' => array(
      array(
        'name' => 'data',
        'type' => 'struct',
        'description' => 'The rubric item object',
        'source' => 'data',
        'optional' => FALSE,
      ),
    ),
  );
  $update = array(
    'help' => 'Updates a rubric item',
    'callback' => '_exri_update',
    'access callback' => '_exri_access',
    'access arguments' => array('update'),
    'access arguments append' => TRUE,
    'args' => array(
      array(
        'name' => 'id',
        'type' => 'int',
        'description' => 'The id of the rubric item to update',
        'source' => array('path' => '0'),
        'optional' => FALSE,
      ),
      array(
        'name' => 'data',
        'type' => 'struct',
        'description' => 'The rubric item data object',
        'source' => 'data',
        'optional' => FALSE,
      ),
    ),
  );
  $delete = array(
    'help' => 'Deletes a rubric item',
    'callback' => '_exri_delete',
    'access callback' => '_exri_access',
    'access arguments' => array('delete'),
    'access arguments append' => TRUE,
    'args' => array(
      array(
        'name' => 'nid',
        'type' => 'int',
        'description' => 'The id of the rubric item to delete',
        'source' => array('path' => '0'),
        'optional' => FALSE,
      ),
    ),
  );
  $index = array(
    'help' => 'Retrieves a listing of rubric items',
    'callback' => '_exri_index',
    'access callback' => '_exri_access',
    'access arguments' => array('access content'),
    'access arguments append' => FALSE,
    'args' => array(
      array(
        'name' => 'page',
        'type' => 'int',
        'description' => '',
        'source' => array(
          'param' => 'page',
        ),
        'optional' => TRUE,
        'default value' => 0,
      ),
      array(
        'name' => 'parameters',
        'type' => 'array',
        'description' => '',
        'source' => 'param',
        'optional' => TRUE,
        'default value' => array(),
      ),
    ),
  );
  $actions = array(
    //For rubric select interface on exercise forms.
    'getTitlesCategories' => array(
      'help' => 'Get all rubric item titles and their categories',
      'callback' => '_exri_titles_cats',
      'access callback' => '_exri_access',
      'access arguments' => array('access content'),
      'access arguments append' => TRUE,
    ),
    //Check that a title is OK.
    'chkTtl' => array(
      'help' => 'Check that a title doesn\'t conflict with an existing one',
      'callback' => '_exri_check_title',
      'access callback' => '_exri_access',
      'access arguments' => array('access content'),
      'access arguments append' => TRUE,
       'args' => array(
         array(
          'name' => 'data',
          'type' => 'struct',
          'description' => 'The nid and title',
          'source' => 'data',
          'optional' => FALSE,
        ),
//         array(
//           'name' => 'nid',
//           'type' => 'int',
//           'description' => 'A node id',
//           'source' => array('path' => '0'),
//           'optional' => FALSE,
//         ),
//         array(
//           'name' => 'title',
//           'type' => 'struct',
//           'description' => 'A title for the rubtic item',
//           'source' => 'data',  //array('data' => 'title'),
//           'optional' => FALSE,
//         ),
       ),

    ),
  );
  $api = array(
   'operations' => array(
     'retrieve' => $retrieve,
     'create' => $create,
     'update' => $update,
     'delete' => $delete,
     'index' => $index,
    ),
    'actions' => $actions,
  );
  return $api;
}


function _cybercourse_exercise_def_exercise_services() {
  $api = array(
      'operations' => array(
       'retrieve' => array(
         'help' => 'Retrieves an exercise',
         'callback' => '_exex_retrieve',
         'access callback' => '_exex_access',
         'access arguments' => array('view'),
         'access arguments append' => TRUE,
         'args' => array(
           array(
             'name' => 'id',
             'type' => 'int',
             'description' => 'The id of the exercise to get',
             'source' => array('path' => '0'),
             'optional' => FALSE,
           ),
         ),
       ),
     ),
    ); // End exercise
  return $api;
}


function _cybercourse_exercise_def_category_services() {
  $api = array(
      'actions' => array(
        'getTree' => array(
          'help'   => t('Returns a full list of taxonomy terms.'),
          'access arguments' => array('access content'),
          'callback' => '_cycoex_get_tree',
        ),
      ),
    ); //End rubric_item_categories
  return $api;
}

/**
 * Define API for client asking server for metadata about one student's
 * submissions for one exercise.
 * @return array Definition.
 */
function _cybercourse_exercise_def_sub_meta_services() {
  $api = array(
      'actions' => array(
        'getSubmissionMetaStudentExer' => array(
          'help' => 
            t('Returns a list of one student\'s submissions for one exercise .'),
          'access arguments' => array('access content'),
          'callback' => '_cycoex_get_sub_meta_student_exer',
       'args' => array(
         array(
          'name' => 'data',
          'type' => 'struct',
          'description' => 'The student\'s uid and exercise nid',
          'source' => 'data',
          'optional' => FALSE,
          ),
        ), //End args.
//        'args' => array(
//            array(
//              'name' => 'student_uid',
//              'type' => 'int',
//              'description' => 'The id of the student',
//              'source' => array('path' => '0'),
//              'optional' => FALSE,
//            ),
//            array(
//              'name' => 'exercise_nid',
//              'type' => 'int',
//              'description' => 'The id of the exercise',
//              'source' => array('path' => '1'),
//              'optional' => FALSE,
//            ),
//          ), //End args.
          
        ),
      ),
    ); //End rubric_item_categories
  return $api;
}

/********************************************
* Rubric items
*********************************************/

/**
 * Check user access to rubric items. Called during Ajax.
 * @global stdCls $user Current user.
 * @param string $operation What to do, e.g., view, edit, delete.
 * @param array $args Arguments passed in.
 * @return boolean True if access allowed, else false.
 */
function _exri_access($operation, $args) {
  return TRUE;
  global $user;
  $access = FALSE;
  $nid = $args[0];
  $node = node_load($nid);
  $access = node_access($operation, $node);
  return $access;
  switch ($operation) {
    case 'view':
      //View access check depends on content_access module.
      $access = user_access('view any rubric_item content');
      $access = $access 
          || ( $node->uid == $user->uid && user_access('view own rubric item') );
      break;
    case 'update':
      $access = user_access('edit any rubric item');
      $access = $access 
          || ( $node->uid == $user->uid && user_access('edit own rubric item') );
      break;
    case 'delete':
      $note = noteresource_get_note($args[0]);
      $access = user_access('delete any rubric item');
      $access = $access 
          || $note->uid == $user->uid && user_access('delete own rubric item');
      break;
  }
  return $access;
}

/**
 * Retrieve a rubric item.
 * @param int $nid Node id.
 * @return \stdClass Item.
 */
function _exri_retrieve( $nid ){
  //Load the node.
  $node = node_load($nid);
  if ( ! $node || $node->type != 'rubric_item') {
    $message = __FILE__ . ' (line ' . __LINE__ . ') ' . __FUNCTION__ 
        . ' Cannot load node: ' . $nid;
    cybercourse_services_handle_error( 'UNKNOWN_NODE', $message );
    return;
  }
  $rubric_item = new stdClass();
  $rubric_item->nid = $nid;
  //Put title in result.
  $rubric_item->title = $node->title;
  //Put notes in result, if there are any.
  $rubric_item->notes = '';
  if ( isset( $node->field_body[LANGUAGE_NONE][0]['pure_rest'] ) ) {
    $rubric_item->notes = $node->field_body[LANGUAGE_NONE][0]['pure_rest'];
  }
  //Put the categories (a vocab) into the results.
  $rubric_item->termsChecked = array();
  if ( isset( $node->field_categories[LANGUAGE_NONE][0]['tid'] ) ) {
    foreach ( $node->field_categories[LANGUAGE_NONE] as $key => $value ) {
      $tid = $value['tid'];
      $rubric_item->termsChecked[] = $tid;
    }
  }
  //Put the good phrases into the results.
  $rubric_item->phrasesGood = array();
  if ( isset( $node->field_feedback_good[LANGUAGE_NONE][0]['value'] ) ) {
    foreach ( $node->field_feedback_good[LANGUAGE_NONE] as $key => $value ) {
      $tid = $value['value'];
      $rubric_item->phrasesGood[] = $tid;
    }
  }
  //Put the needs_work phrases into the results.
  $rubric_item->phrasesNeedsWork = array();
  if ( isset( $node->field_feedback_needs_work[LANGUAGE_NONE][0]['value'] ) ) {
    foreach ( $node->field_feedback_needs_work[LANGUAGE_NONE] as $key => $value ) {
      $tid = $value['value'];
      $rubric_item->phrasesNeedsWork[] = $tid;
    }
  }  
  //Put the poor phrases into the results.
  $rubric_item->phrasesPoor = array();
  if ( isset( $node->field_feedback_poor[LANGUAGE_NONE][0]['value'] ) ) {
    foreach ( $node->field_feedback_poor[LANGUAGE_NONE] as $key => $value ) {
      $tid = $value['value'];
      $rubric_item->phrasesPoor[] = $tid;
    }
  }
  return $rubric_item;
}

/**
 * Create a new rubric item.
 * @param array $data Data from client about the rubric item.
 */
function _exri_create($data){
  global $user;
  $node = new stdClass();
  $node->title = $data['title'];
  $node->type = 'rubric_item';
  node_object_prepare($node);
  $node->language = LANGUAGE_NONE;
  $node->uid = $user->uid;
  $node->status = 1; 
  $node->promote = 0;
  $node->comment = 0; // 0 = comments disabled, 1 = read only, 2 = read/write
  if ( $data['notes'] ) {
    $node->field_body[LANGUAGE_NONE][0]['pure_rest'] = $data['notes'];
  }
  else {
    $node->field_body = array();
  }
  $node->field_categories = 
       _cyco_exer_move_arr_into_node( $data['termsChecked'], 'tid');
  $node->field_feedback_good = 
      _cyco_exer_move_arr_into_node($data['phrasesGood'], 'value');
  $node->field_feedback_needs_work = 
      _cyco_exer_move_arr_into_node($data['phrasesNeedsWork'], 'value');
  $node->field_feedback_poor = 
      _cyco_exer_move_arr_into_node($data['phrasesPoor'], 'value');

  $node = node_submit($node); // Prepare node for saving
  node_save($node);  
  $result = new stdClass();
  $result->operation = 'create';
  $result->nid = $node->nid;
  $result->status = 'OK';
  return $result;

}

function _exri_update($nid, $data){
  //Load the node, check it is there.
  $node = node_load( $nid );
  $node->title = $data['title'];
  if ( $data['notes'] ) {
    $node->field_body[LANGUAGE_NONE][0]['pure_rest'] = $data['notes'];
  }
  else {
    $node->field_body = array();
  }
  $node->field_categories = 
       _cyco_exer_move_arr_into_node( $data['termsChecked'], 'tid');
  $node->field_feedback_good = 
      _cyco_exer_move_arr_into_node($data['phrasesGood'], 'value');
  $node->field_feedback_needs_work = 
      _cyco_exer_move_arr_into_node($data['phrasesNeedsWork'], 'value');
  $node->field_feedback_poor = 
      _cyco_exer_move_arr_into_node($data['phrasesPoor'], 'value');
//  $node->field_feedback_good[LANGUAGE_NONE][0]['value'];
//  $node->field_feedback_needs_work[LANGUAGE_NONE][0]['value'];
//  $node->field_feedback_poor[LANGUAGE_NONE][0]['value']; 
  node_save($node);
  $result = new stdClass();
  $result->operation = 'update';
  $result->nid = $nid;
  $result->status = 'OK';
  return $result;
}

/**
 * Restructure data from flat array into structure used in multivalued
 * Drupal fields.
 * @param type $source Data to restructure.
 * @param type $inner_key Key to use to store data in field elements. 
 * @return array Data structured as values on a node's field.
 */
function _cyco_exer_move_arr_into_node( $source, $inner_key ) {
  $result = array();
  if ( sizeof($source) > 0 ) {
    for ( $i = 0; $i < sizeof($source); $i++) {
      $result[LANGUAGE_NONE][$i][$inner_key] = $source[$i];
    }
  }
  return $result;
}

function _exri_delete(){}

function _exri_index(){}

/**
 * Return all rubric item titles and their categories.
 */
function _exri_titles_cats() {
  //Get all the nids of the published rubric items.
  $query = new EntityFieldQuery;
  $query
    ->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'rubric_item')
    ->propertyCondition('status', 1)
    ->propertyOrderBy('title');
  $query_result = $query->execute();
  //Create the pseudent HTML.
  $nids = array();
  foreach ( $query_result['node'] as $nid => $value ) {  
    $nids[] = $nid;
  }
  $nodes = node_load_multiple($nids);
  $result = array();
  foreach ( $nodes as $node ) {
    $nid = intval( $node->nid );
    $title = $node->title;
    $categories = array();
    if ( isset($node->field_categories[LANGUAGE_NONE]) ) {
      foreach ( $node->field_categories[LANGUAGE_NONE] as $key => $tid ) {
        $categories[] = intval($tid['tid']);
      }
    }
    $result[] = array(
      'nid' => $nid,
      'title' => $title,
      'categories' => $categories,
    );
  }
  return $result;
}

/********************************************
* Rubric item categories
*********************************************/


function _exric_access() {
  return TRUE;
}

function _exric_retrieve( $tid ){
  $thing = new stdClass();
  $thing->heads = 7;
  return $thing;
//  return json_encode($thing);
  
  $node = node_load($nid);
  if ( ! $node || $node->type != 'rubric_item') {
    services_error('Not a rubric item', 666, $nid);
  }
  $rubric_item = new stdClass();
  $rubric_item->type = $node->type;
  $rubric_item->title = $node->title;
  $rubric_item->body = $node->body[LANGUAGE_NONE][0]['value'];
  return  $rubric_item;
}

/**
 * Return terms from the rubric item categories vocab.
 */
function _exric_index() {
  $rubric_item_tree = new stdClass();
  $rubric_item_tree->type = 'evil';
  return $rubric_item_tree;  
}

/**
 * Check user access to exercises. Called during Ajax.
 * @global stdCls $user Current user.
 * @param string $operation What to do, e.g., view, edit, delete.
 * @param array $args Arguments passed in.
 * @return boolean True if access allowed, else false.
 */
function _exex_access($operation, $args) {
  global $user;
  $access = FALSE;
  $nid = $args[0];
  $node = node_load($nid);
  switch ($operation) {
    case 'view':
      //View access check depends on content_access module.
      $access = user_access('view any exercise');
      $access = $access 
          || ( $node->uid == $user->uid && user_access('view own exercise') );
      break;
    case 'update':
      $access = user_access('edit any exercise');
      $access = $access 
          || ( $node->uid == $user->uid && user_access('edit own exercise') );
      break;
    case 'delete':
      $note = noteresource_get_note($args[0]);
      $access = user_access('delete any exercise');
      $access = $access 
          || $note->uid == $user->uid && user_access('delete own exercise');
      break;
  }
  return $access;
}

function _exex_retrieve(){}

function _exex_create(){}

function _exex_update(){}

function _exex_delete(){}

function _exex_index(){}

/**
 * Get the rubric item vocabulary.
 * @return \stdClass The vocab.
 */
function _cycoex_get_tree() {
//  services_error('Not a rubric item', 666, $nid);
  //Get the vid of the Feedback items categoes vocab.
  $vocab = taxonomy_vocabulary_machine_name_load('rubric_item_categories');
  if ( $vocab === FALSE ) {
    $message = __FILE__ . ' (line ' . __LINE__ . ') ' . __FUNCTION__ 
        . ' Cannot find vocab rubric_item_categories.';
    cybercourse_services_handle_error( 'UNKNOWN_VOCAB', $message );
    return;
  }
  $terms = taxonomy_get_tree($vocab->vid);
  $tree = array();
  foreach ( $terms as $term ) {
    $term_data = new stdClass();
    $term_data->tid = intval($term->tid);
    $term_data->title = $term->name;
    $term_data->parent_tid = intval($term->parents[0]);
    $tree[] = $term_data;
  }
  return $tree;
}

function _cycoex_attach_2_parent( $tree, $child, $parent_id ) {
  
}

/**
 * Check whether a title is in use for a rubric item.
 * @param integer $nid_to_check Node id. 0 for new node.
 * @param string $title_to_check Title to check.
 * @return \stdClass Result send to client.
 */
function _exri_check_title( $data ) {
  if ( !isset($data['nid']) ) {
    $message = __FILE__ . ' (line ' . __LINE__ . ') ' . __FUNCTION__ 
        . ' nid missing.';
    cybercourse_services_handle_error( 'NID_MISSING', $message );
    return;
  }
  if ( !isset($data['title']) || strlen($data['title']) == 0 ) {
    $message = __FILE__ . ' (line ' . __LINE__ . ') ' . __FUNCTION__ 
        . ' Title missing.';
    cybercourse_services_handle_error( 'TITLE_MISSING', $message );
    return;
  }
  $nid_to_check = $data['nid'];
  $title_to_check = $data['title'];
  $title_to_check = trim($title_to_check);
  if ( ! is_numeric($nid_to_check) || $nid_to_check < -1 ) {
    $message = __FILE__ . ' (line ' . __LINE__ . ') ' . __FUNCTION__ 
        . ' Invalid nid: ' . $nid;
    cybercourse_services_handle_error( 'INVALID_NID', $message );
    return;
  }
  //Find a rubric with that title.
  $query = new EntityFieldQuery;
  $query
    ->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'rubric_item')
    ->propertyCondition('status', 1)
    ->propertyCondition('title', $title_to_check);
  $query_result = $query->execute();
  //Move data into an array.
  $result_nids = array();
  foreach ( $query_result['node'] as $result_nid => $value ) {  
    $result_nids[] = $result_nid;
  }
  $warn_user = TRUE;
  if ( sizeof($result_nids) == 0 ) {
    //Unique title.
    $warn_user = FALSE;
  }
  else if ( sizeof($result_nids) == 1 ) {
    if ( $result_nids[0] == $nid_to_check ) {
      //Title hasn't changed for the item.
      $warn_user = FALSE;
    }
    else {
      $warn_user = TRUE;
    }
  } 
  else {
    $warn_user = TRUE;
  }
  //Does the user need a warning about the title?
  $result = new stdClass();
  $result->warn = $warn_user;
  return $result;
}

/**
 * Get metadata about one student's submissions for one exercise.
 * Uid in request must match logged in user, or the logged in user
 * must have special priveleges.
 * Dates are ISO8601.
 * @return \stdClass
 */
function _cycoex_get_sub_meta_student_exer( $data ) {
  //Get params.
  if ( !isset($data['student']) ) {
    $message = __FILE__ . ' (line ' . __LINE__ . ') ' . __FUNCTION__ 
        . ' student uid missing.';
    cybercourse_services_handle_error( 'UID_MISSING', $message );
    return;
  }
  if ( !isset($data['exercise']) ) {
    $message = __FILE__ . ' (line ' . __LINE__ . ') ' . __FUNCTION__ 
        . ' exercise nid missing missing.';
    cybercourse_services_handle_error( 'NID_MISSING', $message );
    return;
  }
  $student_uid = $data['student'];
  $exercise_nid = $data['exercise'];
  //Check user has permission.
  $permission = FALSE;
  global $user;
  if ( $student_uid == $user->uid ) {
    $permission = TRUE;
  }
  else if ( cybercourse_base_current_user_has_role( 
            array('administrator', 'instructor', 'grader') ) 
          ) {
    $permission = TRUE;
  }
  if ( ! $permission ) {
    $message = __FILE__ . ' (line ' . __LINE__ . ') ' . __FUNCTION__ 
        . ' Cannot load submissions. Exercise: ' . $exercise_nid 
        . ' User: ' . $student_uid;
    cybercourse_services_handle_error( 'ACCESS_DENIED', $message );
    return;
  }
  //Run the view.
  $view = views_get_view('submission_metadata_for_student_exercise');
  $view->set_arguments(array( $student_uid, $exercise_nid, ));
  $view->execute();
  if ( ! $view->executed ) {
    $message = __FILE__ . ' (line ' . __LINE__ . ') ' . __FUNCTION__ 
        . ' Cannot run submission metadata view. Exercise:' . $exercise_nid 
        . ' user ' . $student_uid;
    cybercourse_services_handle_error( 'VIEW_RUN_FAILURE', $message );
    return;
  }
  $view_results = $view->result;
  $submissions = array();
  foreach( $view_results as $view_result ) {
    $submisson = array();
    $submisson['nid'] = $view_result->nid;
    $submisson['version'] = $view_result->field_field_version[0]['raw']['value'];
    $submisson['whenCreated'] = cybercourse_base_timestamp_to_iso6801(
        $view_result->node_created
    );
    $submisson['whenSubmitted'] = 
        isset( $view_result->field_field_when_submitted[0] )
        ? $view_result->field_field_when_submitted[0]['raw']['value']
        : '';
    $submisson['whenFeedbackGiven'] = 
        isset( $view_result->field_field_when_feedback_given[0] )
        ? $view_result->field_field_when_feedback_given[0]['raw']['value']
        : '';
    $submisson['complete'] = 
        $view_result->field_field_complete[0]['raw']['value'];
    $submissions[] = $submisson;
  }
  return $submissions;
}


/**
 * Handle a services error.
 * @staticvar CyberCourseErrorHandler $error_handler Error handling class.
 * @param string $error_code Code, e.g., ACCESS_DENIED.
 * @param string $explanation Why? Oh, god, WHY?
 */
function cybercourse_services_handle_error( 
      $error_code = 'UNKNOWN_ERROR',
      $explanation = 'Something bad.'
    ) {
    cybercourse_base_handle_error($error_code, $explanation);
    //Return to client.
    services_error($error_code . '. ' . $explanation);
}


function _cybercourse_exercise_def_feedback_services() {
  $api = array(
      'actions' => array(
        'getGraderSubmissionsNeedingFeedback' => array(
          'help' => t('Returns a list of submissions needing feedback from the current user.'),
          'access arguments' => array('access content'),
          'callback' => '_cycoex_get_grader_sub_need_feedback',
        ),
      ),
    ); //End rubric_item_categories
  return $api;
}

/**
 * Get the submissions ready for the current user to grade.
 * @return array Submission data.
 */
function _cycoex_get_grader_sub_need_feedback() {
  $submissions = _cybercourse_exercise_get_submissions_to_grade();
  return $submissions;
}

