<?php

module_load_include('inc', 'book', 'book.admin');

function cybercourse_change_rearrange_form_form_book_admin_edit_alter(&$form, &$form_state) {
  $form['save']['#value'] = t('Save');
  $form['cybercourse_instructions'] = array(
    '#markup' => 
      '<p class="rearrange-form-instructions">' .
      t('Drag-and-drop to rearrage pages. You can change titles as well.') .
      '</p><p>' .
      t('Unpublished pages are not shown.') .
      '</p>',
    '#weight' => -10,
  );
//  foreach ( $form['table'] as $key => $entry ) {
//    if ( isset( $entry['title']['#size'] ) ) {
//      $form['table'][$key]['title']['#size'] = 30;
//      $entry['title']['#size'] = 30;
//    }
//  }
}

/**
 * Implements hook_menu_breadcrumb_alter().
 * Remove the breadcrumb from the rearrange page.
 */
function cybercourse_change_rearrange_form_menu_breadcrumb_alter(&$active_trail, $item) {
  $to_find = 'admin/content/book';
  if (substr( current_path(), 0, strlen($to_find) ) == $to_find ) {
    $active_trail = array();
  }
}
//
///**
// * Implements hook_menu_alter().
// * Changes permission check for altering settings.
// */
//function cybercourse_change_rearrange_form_menu_alter(&$items) {
//  //Adapted from system.module.
//  foreach (list_themes() as $theme) {
//    $items['admin/appearance/settings/' . $theme->name] = array(
//      'title' => $theme->info['name'],
//      'page arguments' => array('system_theme_settings', $theme->name),
//      'type' => MENU_NORMAL_ITEM,
//      'access callback' => '_dts_system_settings_access',
//      'access arguments' => array($theme->name),
//    );
//  }
//  //Change the function called to check access to book rearranging.
//  $items['admin/content/book/%node'] = array(
//    'title' => 'Rearrange book pages and change titles',
//    'page callback' => 'drupal_get_form',
//    'page arguments' => array('book_admin_edit', 3),
//    'access callback' => '_dcrf_check_rearrange_access',
//    'access arguments' => array(3),
//    'type' => MENU_CALLBACK,
////    'file' => 'book.admin.inc',
//  );  
//}
//
///**
// * Check whether the user is allowed to mess with the book.
// */
//function _dcrf_check_rearrange_access($node) {
//  global $user;
//  //Admins are SUPER!
//  if ( $user->uid == 1 || in_array('administrator', $user->roles) ) {
//    return TRUE;
//  }
//  $ok = domain_reference_roles_node_access($node, 'update');
//  return $ok;
//}


/**
 * For unpublished book page, add a message where the 'make a kid' link
 * normally is.
 * @param type $build
 */
//function cybercourse_change_rearrange_form_menu_local_tasks_alter(&$data, $router_item, $root_path) {
//  drupal_set_message(999);
//function cybercourse_change_rearrange_form_node_view_alter(&$build) {
//  $node = $build['#node'];
//  if ( isset( $node->book['bid'] )  ) {
//    $bid = $node->book['bid'];
//    $book_node = node_load($bid);
//    $can_rearrange = domain_reference_roles_node_access($book_node, 'update');
//    if ( $can_rearrange ) {
//      
//    }
//  }
  
//}