<?php
//function cybercourse_change_blocks_block_view_markdown_help_alter(&$data, $block) {
//  $r=5;
//}
//hook_block_view_MODULE_DELTA_alter

//function cybercourse_change_blocks_block_view_alter(&$data, $block) {
//  if ( $block->delta == 'markdown_help' ) {
//    $data['title'] = 'Editing tips';
//    $data['content'] = 
//'<p>' . t('
//Blank lines separate paragraphs. Press Enter twice to make one.
//') . '</p>
//<p><code>' . t('# Header 1<br>
//## Header 2<br>
//### Header 3<br>
//#### Header 4<br>
//##### Header 5
//') . '</code></p>
//<p>' . t('Link:') . '<br><code>' . t('[CyberCourse](http://cybercour.se)') . '</code></p>
//<p>' . t('Inline markup like ') . '<code>_' . t('italics') . '_</code>,
// and <code>**' . t('bold') . '**</code>.</p>
//<p><code> > ' . t('This is a quote.') . '</code></p>
//<p><code>* ' . t('Bulleted lists.') . '<br>
//        * ' . t('Put blank lines') . '<br>
//        * ' . t('around them.') . '
//</code></p>
//<p><code>1. ' . t('A numbered list') . '<br>
//1. ' . t('Is like this.') . '<br>
//1. ' . t('Another one.') . '
//</code></p>
//<p>' . t('Use the preview button to see how your content will look on '
//. 'different devices.') . '
//</p>
//<p>' . t('See the <a href="http://cybercour.se">CyberCourse wiki</a> for more.') . '
//</p>';
//  } // End if
//}
