<?php

function km_modal_form_test_init() {
//  drupal_add_library('system', 'drupal.ajax');
//  drupal_add_library('dialog','dialog');
}

function km_modal_form_test_block_info() {
  $blocks = array();
  $blocks['km_modal_form_test_form'] = array(
    'info' => t('Test'),
  );
  return $blocks;
}

function km_modal_form_test_block_view($delta = '') {
  drupal_add_library('dialog','dialog');
  $block = array();
  switch ($delta) {
    case 'km_modal_form_test_form':
      $block['subject'] = t('Test');
      $block['content'] = l(
          'Simple test', 
          't1/nojs', 
          array('attributes' => 
            array('class' => array('use-ajax', 'use-dialog')),
          )
      );
      break;
  }
  return $block;
}

function km_modal_form_test_menu() {
  $items = array();
  $items['t1/%dialog_js'] = array(
    'title' => 'Test form',
    'page callback' => 't1',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['t1-done/%'] = array(
    'title' => 'Test form',
    'page callback' => 't1_done',
        'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );  
  return $items;
}

function t1($ajax) {
  drupal_add_library('dialog','dialog');
  if ( $ajax ) {
    //dialog_display(TRUE);
    $form_def = drupal_get_form('t1_form');
//    if (TRUE) { 
      $commands = array();
      $commands[] = dialog_command_display($form_def, array(
        'title' => t('Test form'),
        'width' => '500',
        'height' => 'auto',
        'position' => 'center',
      ));
//    }
//    else {
//      $commands[] = dialog_command_reload();
//    }
  //  ajax_render($commands);
    ajax_deliver(array('#type' => 'ajax', '#commands' => $commands));
  }
  else {
    return 'NOwt';
  }
}

function t1_form() {
//    drupal_add_library('system', 'drupal.ajax');
  $form = array();
  $form['#attached']['library'] = array(
    array('dialog', 'dialog'),
  );
  $form['intro'] = array(
    '#markup' => 'Intro text',
  );
  $form['name'] = array(
    '#type' => 'textfield',
  );

$form['submit'] = array(
  '#type' => 'submit',
  '#value' =>'go',
  '#attributes' => array('class' => array('use-ajax-submit')),
);
    
  $form['#process'][] = 'dialog_process_ajax_form';
  $form['#submit'][] = 't1_form_submit';
  //$form['#submit'][] = 't1_form_submit';
  //$form_state['redirect'] = 't1-done';
  return $form;
}

function t1_form_submit($form, &$form_state) {
  //drupal_static_reset('dialog_display');
  $name = $form_state['values']['name'];
  $form_state['redirect'] = 't1-done/' . $name;
}

function t1_done($name) {
  //drupal_add_library('system', 'drupal.ajax');
  //drupal_add_library('system', 'jquery.form');
  $commands = array();
  $commands[] = ajax_command_alert('DONE ' . $name);
  $commands[] = dialog_command_dismiss();
  ajax_deliver(array('#type' => 'ajax', '#commands' => $commands));
}
